### ISSUE TITLE
when enabled, fatal error when adding a field to a content type

### ISSUE THREAD

**Issue by juliencarnot** [OlgaRabodzei/conditional_fields#1]
After installing the module, when I add a field to a content type, I get the WSOD when saving or trying to edit it. Here is the message in the log.

`InvalidArgumentException: EntityDisplay entities can only handle fieldable entity types. in Drupal\Core\Entity\EntityDisplayBase->__construct() (line 126 of /var/www/html/core/lib/Drupal/Core/Entity/EntityDisplayBase.php).`

Removing the module solves the problem.

**Comment by OlgaRabodzei** [comment]
Hello, Julien!
Thanks for Your response. The bug was fixed.
I would be very pleased, if You checked it.

**Comment by juliencarnot** [comment]
fix confirmed, thanks!
