### ISSUE TITLE
Conditional fields table labels UX

### ISSUE THREAD

**Issue by zerolab** [OlgaRabodzei/conditional_fields#11]
Found myself constantly getting it wrong when adding the fields.

I suggest renaming the label from "Dependant"/"Dependee" to "Field" ("Target field") / "Controlled by".

<del>Additionally, the variables should follow a similar naming convention for clarity.
Have been researching around and "dependee" is not a correct term. Normally this is a "parent"/"master". But "$controller" / "$target" are good candidates</del>
**edit** I see that core states.js uses dependent/dependee, so this is in line with core. I still think the UI labels could be less technical.

**Comment by OlgaRabodzei** [comment]
Resolved in the last dev release (2017-Jan-24) on 
https://www.drupal.org/project/conditional_fields
