### ISSUE TITLE
Fatal error when editing content type

### ISSUE THREAD

**Issue by attheshow** [OlgaRabodzei/conditional_fields#2]
When going to the basic form to edit a content type I'm getting the following error:

> Fatal error: Call to undefined method Drupal\node\Entity\NodeType::getType() in /var/www/drupalvm/d8sandbox.com/modules/contrib/conditional_fields/conditional_fields.module on line 190

**Comment by attheshow** [comment]
Commenting out lines 188-221 appears to remove the fatal error.

**Comment by OlgaRabodzei** [comment]
Hello, Mark!
Thanks for Your response. The bug was fixed.
I would be very pleased, if You checked it.

**Comment by attheshow** [comment]
This appears to be fixed. Thanks!
