### ISSUE TITLE
Missing "Manage Dependencies" Tab

### ISSUE THREAD

**Issue by attheshow** [OlgaRabodzei/conditional_fields#3]
Maybe I'm missing something. I was expecting to see the "Manage Dependencies" tab in order to manage the conditional fields on my content types after enabling the module, but this doesn't appear to be present as it was in D7. Is this an intentional change?

**Comment by OlgaRabodzei** [comment]
Hello, Mark!
"Manage Dependencies" tab on content types is in plans.

**Comment by OlgaRabodzei** [comment]
The condition field menu was updated. Now instead of dropdown lists we have menu steps. I suppose it looks much better. Also edit tabs are planed on each content type edit page.

**Comment by zerolab** [comment]
Per https://www.drupal.org/node/2830991, this should be fixed.

**Comment by OlgaRabodzei** [comment]
Resolved in the last dev release (2017-Jan-24) on 
https://www.drupal.org/project/conditional_fields
