### ISSUE TITLE
"Insert value from widget...": widget doesn't display

### ISSUE THREAD

**Issue by juliencarnot** [OlgaRabodzei/conditional_fields#4]
When choosing Values input mode "Insert value from widget...", the widget is not displayed below.

**Comment by OlgaRabodzei** [comment]
Hi, Julien!
It's known issue. There is a TODO mark in the code for it.
https://github.com/OlgaRabodzei/conditional_fields/blob/master/src/Form/ConditionalFieldEditForm.php#L111

**Comment by juliencarnot** [comment]
Thanks for the info! Is there a roadmap/todo list somewhere for other known issues?

**Comment by OlgaRabodzei** [comment]
I'm thinking about creating a checklist till the end of next week.
A TODO list from IDE is all that I could provide You for now. Sorry. 
Also I need to say that some positions moved from the version for drupal 7.
![selection_123](https://cloud.githubusercontent.com/assets/1485839/18913473/a216559e-8590-11e6-8b6a-e3f8f517bb6d.png)

**Comment by juliencarnot** [comment]
Thanks Olga, this is helpful already!

**Comment by OlgaRabodzei** [comment]
The widget is visible now, but we still have problems with it. So the task in still in progress.

**Comment by attheshow** [comment]
I ran into this problem as well. As a workaround, I changed my conditional to use the "Values input mode: All these values (AND)..." and then explicitly typed in the value that I was looking for. It's working after that.

**Comment by juliencarnot** [comment]
Closing this issue to clear the queue here, as the readme.md file is now explicit about the work in progress on that issue.
