### ISSUE TITLE
Limit dependet/dependee select widths in the management screen

### ISSUE THREAD

**Issue by zerolab** [OlgaRabodzei/conditional_fields#9]
The selects output the machine name and the label. With sufficiently long labels the conditional fields management screen becomes very wide and the editing UX is rather difficult.

Attaching some CSS to limit the width should be the quickest solution. Can provide a PR if you are happy with that approach.

**Comment by OlgaRabodzei** [comment]
Thank You, Dan. You are right, now it looks better.
